version: '3.4'

services:
  moneytracker-vk:
    image: moneytracker-vk
    build:
      context: .
      dockerfile: ./vk/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ./vk/main.py "]
    ports:
      - 5678:5678

  moneytracker-tg:
    image: moneytracker-tg
    build:
      context: .
      dockerfile: ./tg/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ./tg/start.py "]
    ports:
      - 5678:5678
